In [1]:
import numpy as np

# Creating a 1D NumPy array
array_1d = np.array([1, 2, 3, 4, 5])

# Creating a 2D NumPy array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

print("1D Array:")
print(array_1d)
print("\n2D Array:")
print(array_2d)


1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

# Initial 1D array
array_1d = np.array([1, 2, 3, 4, 5, 6])

# Reshape to 2D array (2 rows, 3 columns)
array_2d = array_1d.reshape(2, 3)

print("Original 1D Array:")
print(array_1d)
print("\nReshaped to 2D Array:")
print(array_2d)


Original 1D Array:
[1 2 3 4 5 6]

Reshaped to 2D Array:
[[1 2 3]
 [4 5 6]]


In [5]:
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Indexing
element = array_2d[1, 2]

# Slicing
slice_2d = array_2d[0:2, 1:3]

print("Element at index [1, 2]:", element)
print("\nSliced Array:")
print(slice_2d)


Element at index [1, 2]: 6

Sliced Array:
[[2 3]
 [5 6]]


In [7]:
import numpy as np

# Creating two 2D arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Vertical stacking
v_stack = np.vstack((array1, array2))

# Horizontal stacking
h_stack = np.hstack((array1, array2))

print("Vertical Stack:")
print(v_stack)
print("\nHorizontal Stack:")
print(h_stack)


Vertical Stack:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Horizontal Stack:
[[1 2 5 6]
 [3 4 7 8]]


In [9]:
import numpy as np

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a 1D array
array_1d = np.array([1, 2, 3])

# Broadcasting
broadcast_result = array_2d + array_1d

print("2D Array:")
print(array_2d)
print("\n1D Array:")
print(array_1d)
print("\nBroadcast Result:")
print(broadcast_result)


2D Array:
[[1 2 3]
 [4 5 6]]

1D Array:
[1 2 3]

Broadcast Result:
[[2 4 6]
 [5 7 9]]
