In [3]:
#Creating a NumPy Array

import numpy as np
# Creating a 1D array from a list
array_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print(array_1d)

# Creating a 2D array (matrix) from a list of lists
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D Array:")
print(array_2d)

# Creating an array with zeros
zeros_array = np.zeros((3, 3))
print("\nArray with Zeros:")
print(zeros_array)

# Creating an array with ones
ones_array = np.ones((2, 4))
print("\nArray with Ones:")
print(ones_array)

# Creating an array with a range of values
range_array = np.arange(10)
print("\nArray with Range of Values:")
print(range_array)

# Creating an array with values in a specified range with a step
step_array = np.arange(0, 10, 2)
print("\nArray with Range of Values and Step:")
print(step_array)

# Creating an array with evenly spaced values
linspace_array = np.linspace(0, 1, 5)
print("\nArray with Evenly Spaced Values:")
print(linspace_array)

# Creating an identity matrix
identity_matrix = np.eye(3)
print("\nIdentity Matrix:")
print(identity_matrix)



1D Array:
[1 2 3 4 5]

2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Array with Zeros:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Array with Ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

Array with Range of Values:
[0 1 2 3 4 5 6 7 8 9]

Array with Range of Values and Step:
[0 2 4 6 8]

Array with Evenly Spaced Values:
[0.   0.25 0.5  0.75 1.  ]

Identity Matrix:
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [5]:
#Shape and Reshaping of NumPy Array

import numpy as np
# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Getting the shape of the array
print("Shape of 2D array:", array_2d.shape)

# Creating a 1D array
array_1d = np.arange(9)
print("\nOriginal 1D Array:")
print(array_1d)

# Reshaping to a 2D array (3x3)
reshaped_array_2d = array_1d.reshape((3, 3))
print("\nReshaped to 2D Array (3x3):")
print(reshaped_array_2d)

# Reshaping to a 3D array (3x3x1)
reshaped_array_3d = array_1d.reshape((3, 3, 1))
print("\nReshaped to 3D Array (3x3x1):")
print(reshaped_array_3d)

# Flattening the 2D array back to 1D
flattened_array = reshaped_array_2d.flatten()
print("\nFlattened back to 1D Array:")
print(flattened_array)

# Using -1 to automatically calculate the dimension
reshaped_with_negative_one = array_1d.reshape((3, -1))
print("\nReshaped with -1 (3x-1):")
print(reshaped_with_negative_one)


Shape of 2D array: (3, 3)

Original 1D Array:
[0 1 2 3 4 5 6 7 8]

Reshaped to 2D Array (3x3):
[[0 1 2]
 [3 4 5]
 [6 7 8]]

Reshaped to 3D Array (3x3x1):
[[[0]
  [1]
  [2]]

 [[3]
  [4]
  [5]]

 [[6]
  [7]
  [8]]]

Flattened back to 1D Array:
[0 1 2 3 4 5 6 7 8]

Reshaped with -1 (3x-1):
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [7]:
#Indexing and Slicing of NumPy Array
import numpy as np

# Creating a 1D array
array_1d = np.array([10, 20, 30, 40, 50])

# Accessing elements by index
print("Element at index 0:", array_1d[0])
print("Element at index 3:", array_1d[3])

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Accessing elements by row and column indices
print("\nElement at (0, 0):", array_2d[0, 0])
print("Element at (1, 2):", array_2d[1, 2])

# Slicing elements from index 1 to 3
slice_1d = array_1d[1:4]
print("\nSliced 1D Array (index 1 to 3):", slice_1d)

# Slicing elements from the beginning to index 3
slice_1d_start = array_1d[:4]
print("Sliced 1D Array (start to index 3):", slice_1d_start)

# Slicing elements from index 2 to the end
slice_1d_end = array_1d[2:]
print("Sliced 1D Array (index 2 to end):", slice_1d_end)

# Slicing a subarray (rows 0 and 1, columns 1 and 2)
slice_2d = array_2d[0:2, 1:3]
print("\nSliced 2D Array (rows 0 and 1, columns 1 and 2):")
print(slice_2d)

# Slicing all rows and specific columns
slice_2d_columns = array_2d[:, 1:3]
print("\nSliced 2D Array (all rows, columns 1 and 2):")
print(slice_2d_columns)

# Slicing specific rows and all columns
slice_2d_rows = array_2d[1:3, :]
print("\nSliced 2D Array (rows 1 and 2, all columns):")
print(slice_2d_rows)

# Creating a new 1D array for fancy indexing
array_fancy = np.array([10, 20, 30, 40, 50])

# Accessing elements at specific indices
fancy_indexed = array_fancy[[0, 2, 4]]
print("\nFancy Indexed 1D Array (indices 0, 2, 4):", fancy_indexed)

# Boolean indexing to get elements greater than 25
bool_indexed = array_fancy[array_fancy > 25]
print("\nBoolean Indexed 1D Array (elements > 25):", bool_indexed)


Element at index 0: 10
Element at index 3: 40

Element at (0, 0): 1
Element at (1, 2): 6

Sliced 1D Array (index 1 to 3): [20 30 40]
Sliced 1D Array (start to index 3): [10 20 30 40]
Sliced 1D Array (index 2 to end): [30 40 50]

Sliced 2D Array (rows 0 and 1, columns 1 and 2):
[[2 3]
 [5 6]]

Sliced 2D Array (all rows, columns 1 and 2):
[[2 3]
 [5 6]
 [8 9]]

Sliced 2D Array (rows 1 and 2, all columns):
[[4 5 6]
 [7 8 9]]

Fancy Indexed 1D Array (indices 0, 2, 4): [10 30 50]

Boolean Indexed 1D Array (elements > 25): [30 40 50]


In [9]:
#Stacking and Concatenating NumPy Arrays, 
import numpy as np
# Creating two 1D arrays
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

# Concatenating along the default axis (axis=0)
concatenated_1d = np.concatenate((array1, array2))
print("Concatenated 1D Array:")
print(concatenated_1d)

# Creating two 2D arrays
array3 = np.array([[1, 2], [3, 4]])
array4 = np.array([[5, 6], [7, 8]])

# Concatenating along axis 0 (rows)
concatenated_2d_axis0 = np.concatenate((array3, array4), axis=0)
print("\nConcatenated 2D Array along axis 0 (rows):")
print(concatenated_2d_axis0)

# Concatenating along axis 1 (columns)
concatenated_2d_axis1 = np.concatenate((array3, array4), axis=1)
print("\nConcatenated 2D Array along axis 1 (columns):")
print(concatenated_2d_axis1)

# Vertical stacking of 1D arrays
vstacked = np.vstack((array1, array2))
print("\nVertically Stacked Array:")
print(vstacked)

# Horizontal stacking of 1D arrays
hstacked = np.hstack((array1, array2))
print("\nHorizontally Stacked Array:")
print(hstacked)

# Creating two new 2D arrays for depth stacking
array5 = np.array([[1, 2], [3, 4]])
array6 = np.array([[5, 6], [7, 8]])

# Depth stacking of 2D arrays
dstacked = np.dstack((array5, array6))
print("\nDepth Stacked Array:")
print(dstacked)

# Stacking along a new axis (axis=0)
stacked_axis0 = np.stack((array1, array2), axis=0)
print("\nStacked along axis 0:")
print(stacked_axis0)

# Stacking along a new axis (axis=1)
stacked_axis1 = np.stack((array1, array2), axis=1)
print("\nStacked along axis 1:")
print(stacked_axis1)


Concatenated 1D Array:
[1 2 3 4 5 6]

Concatenated 2D Array along axis 0 (rows):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated 2D Array along axis 1 (columns):
[[1 2 5 6]
 [3 4 7 8]]

Vertically Stacked Array:
[[1 2 3]
 [4 5 6]]

Horizontally Stacked Array:
[1 2 3 4 5 6]

Depth Stacked Array:
[[[1 5]
  [2 6]]

 [[3 7]
  [4 8]]]

Stacked along axis 0:
[[1 2 3]
 [4 5 6]]

Stacked along axis 1:
[[1 4]
 [2 5]
 [3 6]]


In [11]:
#Broadcasting in NumPy Arrays,
import numpy as np
# Creating a 1D array
array = np.array([1, 2, 3, 4, 5])

# Broadcasting a scalar to the array
result = array + 10
print("Broadcasting a scalar to an array:")
print(result)

# Creating a 2D array
array_2d = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a 1D array
array_1d = np.array([10, 20, 30])

# Broadcasting the 1D array to the 2D array
result_2d = array_2d + array_1d
print("\nBroadcasting a 1D array to a 2D array:")
print(result_2d)

# Creating a 2D array
array_2d_b = np.array([[1, 2, 3], [4, 5, 6]])

# Creating a column vector (2D array)
column_vector = np.array([[10], [20]])

# Broadcasting the column vector to the 2D array
result_b = array_2d_b + column_vector
print("\nBroadcasting a column vector to a 2D array:")
print(result_b)

# Creating a 3D array
array_3d = np.array([[[1, 2, 3], [4, 5, 6]], 
                     [[7, 8, 9], [10, 11, 12]]])

# Creating a 1D array
array_1d_high = np.array([1, 2, 3])

# Broadcasting the 1D array to the 3D array
result_3d = array_3d + array_1d_high
print("\nBroadcasting a 1D array to a 3D array:")
print(result_3d)


Broadcasting a scalar to an array:
[11 12 13 14 15]

Broadcasting a 1D array to a 2D array:
[[11 22 33]
 [14 25 36]]

Broadcasting a column vector to a 2D array:
[[11 12 13]
 [24 25 26]]

Broadcasting a 1D array to a 3D array:
[[[ 2  4  6]
  [ 5  7  9]]

 [[ 8 10 12]
  [11 13 15]]]
